os: linux
install: true
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.0
    - android-29
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository

  licenses:
    - '.+'
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew
  - chmod +x ftp_upload.sh
  - ./gradlew dependencies || true
  
script:
  - ./gradlew :app:assembleRelease --stacktrace

after_script:
  - skip_cleanup: true
  - $TRAVIS_BUILD_DIR/ftp_upload.sh "${TRAVIS_BUILD_DIR}/app/build/outputs/apk/release/app-release-unsigned.apk"
  - cat $HOME/ftp_upload.log
